
name: update

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "*/30 * * * *"   # every 30 mins

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install Dependencies
        run: pip install Jinja2 requests opencv-python
      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/profile/src/
          python update.py
      - name: Push Changes
        run: |
          git config user.name "TSD Github Actions"
          git config user.email "TSD-Github-Actions@users.noreply.github.com"
          git add .
          git commit -am "feat(auto generate): Updated content"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
